### PR TITLE
New new icon, use more physical metaphor, improve symbolic

### PR DESCRIPTION
**Pull request by jannuary**
Seems like I was a bit late, but nevertheless :p

Notes: 
- It might be cleaner and more approachable to define resources in a gresource.xml file.
- Accepted convention is to name icons with the app ID in RDNS format. This doesn't seem to have one, so it's just 'icon'. 
image

### CODE REVIEW

**Comment by nlogozzo** [comment]
This icon doesn't really scream out music tagger to me like our current icon. Seems more of maybe a music player with the record in the back of the icon.

**Comment by jannuary** [comment]
What about this?
image

**Comment by nlogozzo** [comment]
Definitely better. What about if you got rid of the white background with the music note and just made it a full record with the pen in front?

**Comment by jannuary** [comment]
Well, the "white background" is supposed to be a label:
image

**Comment by nlogozzo** [comment]
Definitely like this a lot better! Could you rename the files from com.nickvision.tagger to org.nickvision.tagger as that is the appropriate app id

**Comment by nlogozzo** [comment]
LGTM
Want to get some feedback from [https://github.com/nlogozzo/NickvisionTagger/discussions/15](https://github.com/nlogozzo/NickvisionTagger/discussions/15)

**Comment by nlogozzo** [comment]
Would you be able to have this PR target the [2022.5.4](https://github.com/nlogozzo/NickvisionTagger/tree/2022.5.4) branch so I can test and include this icon in the next release.

**Comment by nlogozzo** [comment]
Could you resolve the conflicts? It seems as after you changed the branch to 2022.5.4, your fork wasn't synced with the changes found in 2022.5.4

**Pull request merged**
