### PR TITLE
Re-created Icon, Looks better, Now follows GNOME HIG

### PR DESCRIPTION
**Pull request by daudix-UFO**
Also working on new icon, For now improved current one
image

### CODE REVIEW

**Comment by nlogozzo** [comment]
👍 beautiful! 
Could you update the readme with the new icon as well?

**Comment by daudix-UFO** [comment]
No problem!

**Comment by daudix-UFO** [comment]
@nlogozzo  Done!

**Comment by nlogozzo** [comment]
Love it thanks! 
I will merge it once I get back on my computer as I'll have to update the paths in the CMakeLists.txt file and in ui/views/mainwindow.cpp as well...unless you want do that as well but no worries

**Comment by daudix-UFO** [comment]
Done!

**Comment by nlogozzo** [comment]
LGTM 
Any more updates to the icons or can I merge?

**Comment by daudix-UFO** [comment]
I think we can merge!

**Comment by nlogozzo** [comment]
Thanks for your contribution! You should see your name in the credits section of the about dialog in the application :)

**Comment by daudix-UFO** [comment]
Thank you, I really happy that you liked my first icon :)

**Comment by nlogozzo** [comment]
It really is amazing, plus It's a million times better than I could ever do. 
Do you have an email/discord or something to communicate...I would like if you could create some icons for other application I have coming down the line

**Comment by nlogozzo** [comment]
If you're not comfortable sharing it here let me know your preferred method and I will give you mine.

**Comment by daudix-UFO** [comment]
Of course I happy to share, my e-mail is: ddaudix@gmail.com , Discord is #3646

**Comment by nlogozzo** [comment]
Discord is easiest for me!
Friend me: nlogozzo#1749

**Pull request merged**
